name: ios_fl_n_wildrama_3398
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  share_plus: ^10.1.4
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2
  font_awesome_flutter: ^10.8.0
  table_calendar: ^3.2.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Atma
      fonts:
        - asset: assets/fonts/Atma-Regular.ttf
          weight: 400
        - asset: assets/fonts/Atma-Medium.ttf
          weight: 500
        - asset: assets/fonts/Atma-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Atma-Bold.ttf
          weight: 700

  assets:
   - assets/
   - assets/fonts/
   - assets/images/
   - assets/images/splash/
   - assets/images/onboarding/
   - assets/images/menu_icons/
   - assets/images/animals/
   - assets/images/flora_animals/
   - assets/images/flora/
   - assets/images/tracks/
